import React from "react";

// const skillData = [
//   { skill: "Java" },
//   { skill: "Python" },
//   { skill: "C Programming" },
//   { skill: "C++" },
//   { skill: "C#" },
//   { skill: "Javascript" },
//   { skill: "NodeJS" },
//   { skill: "HTML" },
//   { skill: "SQL" },
//   { skill: "Adobe Photoshop" },
//   { skill: "Database Management" },
//   { skill: "PHP" },
//   { skill: "UI/UX" },
//   { skill: "Salesforce" },
//   { skill: "Web development" },
//   { skill: "Tableau" },
//   { skill: "Software Architect" },
//   { skill: "Adobe Illustrator" },
//   { skill: "ERP development" },
//   { skill: "Power BI" },
//   { skill: "CRM" },
//   { skill: "Xmind" },
//   { skill: "AWS" },
//   { skill: "Cyber Security" },
//   { skill: "Data Science" },
//   { skill: "Big Data" },
//   { skill: "MS Excel" },
//   { skill: "MS Office" },
//   { skill: "MS Power point" },
//   { skill: "Cloud Computing" },
//   { skill: "Event Management" },
//   { skill: "Communication" },
//   { skill: "Social Media Marketing" },
//   {
//     skill: "Marketing",
//   },
//   { skill: "Email Marketing" },
//   { skill: "SEO planning" },
//   { skill: "Graphic Designing" },
//   { skill: "Sales" },
//   { skill: "Data Analytics" },
//   { skill: "Marketing Analytics" },
//   { skill: "ETL" },
//   { skill: "Online Advertising" },
//   { skill: "Adobe Indesign" },
//   { skill: "Software development" },
//   { skill: "Business development" },
//   { skill: "Frontend development" },
//   { skill: "Backend development" },
//   { skill: "Content Creation" },
//   { skill: "Customer Service" },
//   { skill: "Supply Chain Management" },
//   { skill: "Video Editing" },
//   { skill: "Editing" },
//   { skill: "Employee Training" },
//   { skill: "Forecasting" },
//   { skill: "Business planning" },
//   { skill: "Brand development" },
//   { skill: "KPI Reporting" },
//   { skill: "ReactJs" },
//   { skill: "ExpressJs" },
//   { skill: "BI modeling" },
//   { skill: "Project planning" },
//   { skill: "Photography" },
//   { skill: "Leadership" },
//   { skill: "Networking" },
//   { skill: "Time Management" },
//   { skill: "Listening" },
//   { skill: "Understanding" },
//   { skill: "Decision Making" },
// ];
const skillData = [];
export { skillData };
