const generateHTML = (name, companyName, jobTitle) => {
  return `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office"><head><meta charset="UTF-8"><meta content="width=device-width, initial-scale=1" name="viewport"><meta name="x-apple-disable-message-reformatting"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta content="telephone=no" name="format-detection"><title></title><!--[if (mso 16)]>
                    <style type="text/css">
                    a {text-decoration: none;}
                    </style>
                    <![endif]--><!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]--><!--[if gte mso 9]>
                <xml>
                    <o:OfficeDocumentSettings>
                    <o:AllowPNG></o:AllowPNG>
                    <o:PixelsPerInch>96</o:PixelsPerInch>
                    </o:OfficeDocumentSettings>
                </xml>
                <![endif]--></head><body class="body"><div class="es-wrapper-color"><!--[if gte mso 9]>
                            <v:background xmlns:v="urn:schemas-microsoft-com:vml" fill="t">
                                <v:fill type="tile" color="#fafafa"></v:fill>
                            </v:background>
                        <![endif]--><table class="es-wrapper" width="100%" cellspacing="0" cellpadding="0"><tbody><tr><td class="esd-email-paddings" valign="top"><table cellpadding="0" cellspacing="0" class="es-content esd-header-popover" align="center"><tbody><tr><td class="esd-stripe es-info-area" align="center"><table class="es-content-body" align="center" cellpadding="0" cellspacing="0" width="600" style="background-color: transparent;" bgcolor="rgba(0, 0, 0, 0)"><tbody><tr><td class="esd-structure es-p20" align="left"><table cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td width="560" class="esd-container-frame" align="center" valign="top"><table cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td align="center" class="esd-block-text es-infoblock"><p><a target="_blank">View online version</a></p></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><table cellpadding="0" cellspacing="0" class="es-content" align="center"><tbody><tr><td class="esd-stripe" align="center"><table bgcolor="#ffffff" class="es-content-body" align="center" cellpadding="0" cellspacing="0" width="600"><tbody><tr><td class="esd-structure es-p30t es-p20b es-p20r es-p20l es-m-p20t" align="left"><table cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td width="560" class="esd-container-frame" align="center" valign="top"><table cellpadding="0" cellspacing="0" width="100%"><tbody><tr>
                    <td align="center" class="esd-block-image" style="font-size: 0">
                        <a target="_blank">
                            <img class="adapt-img" src="https://my.stripo.email/uieditor/assets/previews/default-img.png" alt="" width="100%" height="100">
                        </a>
                    </td>
                </tr><tr>
                <td align="center" class="esd-block-text es-p10b es-m-txt-c">
                <h1 style="font-size: 46px; line-height: 100%;">
                Hi ${name}!</h1></td></tr><tr>
                

                <td align="center" class="esd-block-image es-p10t es-p10b" style="font-size: 0px;">
                <a target="_blank" href="https://careersheets.netlify.app/?utm_source=newsletter&utm_medium=email&utm_campaign=job_alerts&utm_id=${companyName}&utm_term=${jobTitle}&utm_content=-">
                <img class="adapt-img" src="https://xgygbb.stripocdn.email/content/guids/CABINET_3f114a28d5cc6bb12f14d8840c12de3814746736aa7f57d80be26a583d1aef6c/images/678.jpg" alt="" style="display:block" width="400"></a></td></tr><tr><td align="center" class="esd-block-text es-p5t es-p5b es-p40r es-p40l es-m-p0r es-m-p0l es-text-2944"><h1 style="font-size:16px;line-height:180% !important">Hiring alert! <span style="color:red; font-weight: bold ">${companyName}</span> is seeking a talented <span style="color:red; font-weight: bold "> ${jobTitle} </span>. Apply today and be part of their dynamic team.</h1></td></tr></tbody></table></td></tr></tbody></table></td></tr><tr><td class="esd-structure es-p10t es-p20r es-p20l" align="left"><table cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td width="560" class="esd-container-frame" align="center" valign="top"><table cellpadding="0" cellspacing="0" width="100%" style="border-left:2px dotted #cccccc;border-right:2px dotted #cccccc;border-top:2px dotted #cccccc;border-bottom:2px dotted #cccccc;border-radius: 5px; border-collapse: separate;"><tbody><tr><td align="center" class="esd-block-text es-p10t es-p10b es-m-txt-c" esd-links-underline="none"><h3><strong>Manage your Job records with</strong></h3><h1><strong><a target="_blank" style="text-decoration: none;" href="https://careersheets.netlify.app/?utm_source=newsletter&utm_medium=email&utm_campaign=job_alerts&utm_id=${companyName}&utm_term=${jobTitle}&utm_content=-">
                Careersheets</a></strong></h1>
                <img src="https://careersheets.netlify.app/static/media/Careersheets-logo.99b72e90818938c99593.png?utm_source=newsletter&utm_medium=email&utm_campaign=job_alerts&utm_id=${companyName}&utm_term=${jobTitle}&utm_content=-"" width="200" height="200" alt="ibacus_logo">
                </td></tr></tbody></table></td></tr><tr><td width="560" class="esd-container-frame" align="center" valign="top"><table cellpadding="0" cellspacing="0" width="100%" style="border-radius: 5px; border-collapse: separate;"><tbody><tr><td align="center" class="esd-block-text es-p10t es-p10b"><p>​</p></td></tr></tbody></table></td></tr></tbody></table></td></tr><tr><td class="esd-structure es-p30b es-p20r es-p20l" align="left"><table cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td width="560" class="esd-container-frame" align="center" valign="top"><table cellpadding="0" cellspacing="0" width="100%" style="border-radius: 5px; border-collapse: separate;"><tbody><tr><td align="center" class="esd-block-button es-p10t es-p10b"><span class="es-button-border" style="border-radius: 6px;"><a href="https://careersheets.netlify.app/?utm_source=newsletter&utm_medium=email&utm_campaign=job_alerts&utm_id=${companyName}&utm_term=${jobTitle}&utm_content=-" class="es-button" target="_blank" style="border-left-width: 30px; border-right-width: 30px; border-radius: 6px;">Login Now</a></span>
                </td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><table cellpadding="0" cellspacing="0" class="es-footer" align="center"><tbody><tr><td class="esd-stripe" align="center"><table class="es-footer-body" align="center" cellpadding="0" cellspacing="0" width="640" style="background-color: transparent;"><tbody><tr>
                <td class="esd-structure es-p20t es-p20b es-p20r es-p20l" align="left"><table cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td width="600" class="esd-container-frame" align="left"><table cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td align="center" class="esd-block-social es-p15t es-p15b" style="font-size:0"><table cellpadding="0" cellspacing="0" class="es-table-not-adapt es-social"><tbody><tr><td align="center" valign="top" class="es-p40r"><a target="_blank" href="https://www.instagram.com/i_bacus_tech/"><img title="Instagram" src="https://xgygbb.stripocdn.email/content/assets/img/social-icons/logo-black/instagram-logo-black.png" alt="Inst" width="32"></a></td><td align="center" valign="top" class="es-p40r"><a target="_blank" href="https://youtu.be/U3wUqrjZTPY?list=TLGGIsLV9x_Sv3gwNjEwMjAyMw"><img title="Youtube" src="https://xgygbb.stripocdn.email/content/assets/img/social-icons/logo-black/youtube-logo-black.png" alt="Yt" width="32"></a></td><td align="center" valign="top"><a target="_blank" href="https://www.linkedin.com/company/ibacustech/mycompany/?viewAsMember=true"><img title="Linkedin" src="https://odhvxu.stripocdn.email/content/assets/img/social-icons/logo-black/linkedin-logo-black.png" alt="In" width="32">
                
                </a></td></tr></tbody></table></td></tr><tr><td align="center" class="esd-block-text es-p35b"><p style="line-height:180% !important"><strong>Viya workspace, Chitra Nagar, Saravanampatti, Coimbatore, </strong></p><p style="line-height:180% !important"><strong>Tamil Nadu 641035</strong></p></td></tr><tr><td class="esd-block-menu" esd-tmp-menu-padding="5|5" esd-tmp-divider="1|solid|#cccccc" esd-tmp-menu-color="#999999"><table cellpadding="0" cellspacing="0" width="100%" class="es-menu"><tbody><tr><td align="center" valign="top" width="33.33%" class="es-p10t es-p10b es-p5r es-p5l" style="padding-top: 5px; padding-bottom: 5px;"><a target="_blank" href="https://www.ibacustech.com/" style="color: #999999;">Visit Us </a></td><td align="center" valign="top" width="33.33%" class="es-p10t es-p10b es-p5r es-p5l" style="padding-top: 5px; padding-bottom: 5px; border-left: 1px solid #cccccc;"><a target="_blank" href="https://www.ibacustech.com/" style="color: #999999;">Privacy Policy</a></td><td align="center" valign="top" width="33.33%" class="es-p10t es-p10b es-p5r es-p5l" style="padding-top: 5px; padding-bottom: 5px; border-left: 1px solid #cccccc;"><a target="_blank" href="https://www.ibacustech.com/" style="color: #999999;">Terms of Use</a></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><table cellpadding="0" cellspacing="0" class="es-content esd-footer-popover" align="center"><tbody><tr><td class="esd-stripe es-info-area" align="center"><table class="es-content-body" align="center" cellpadding="0" cellspacing="0" width="600" style="background-color: transparent;" bgcolor="rgba(0, 0, 0, 0)"><tbody><tr><td class="esd-structure es-p20" align="left"><table cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td width="560" class="esd-container-frame" align="center" valign="top"><table cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td align="center" class="esd-block-text es-infoblock"><p><a target="_blank"></a>No longer want to receive these emails? <a href="" target="_blank">Unsubscribe</a>.<a target="_blank"></a></p></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></div></body></html>`;
};
module.exports = { generateHTML };
